### ISSUE TITLE
haaska function stopped working after switching https (connection error)

### ISSUE THREAD

**Issue by ahmadzeena** [mike-grant/haaska#102]
*sorry if i posted in the wrong place! new to github, let me know if i need to move this somewhere else

Hello,

Alexa integration with home assistant was working beautifully until i switched to https on my home assistant using dehydrated self signed certificate. everything else is working fine including google assistant.

- I've re-done the whole procedure with the amazon/alexa developer and lambda function with the most recent instructions
- I've made sure my port forwarding is configured fine (443,8123-->HA 8123) where my server port is 8123.
- I tried with and without ssl_verify options, with and without a cert.pem/fullchain.pem/[] in the ssl_client.
- locally trying to access https://local:8123/api/, I'm getting 401: Unauthorized
- also https://local:8123/api/alexa/smart_home, I'm getting 405: Method Not Allowed

been trying for 3 days :(

relevant config.yaml:
```

#  auth_providers:
#   - type: legacy_api_password
#   - type: homeassistant

http:
  api_password: "mypassword"
  ssl_certificate: /path/to/my/fullchain.pem
  ssl_key: /path/to/my/privkey.pem
  base_url: "https://myhass.duckdns.org:8123"

api:

alexa:
  smart_home:
```

relevant config.json:
```
{
  "url": "https://myhass.duckdns.org:8123/api",
  "bearer_token": "my-long_lived_token"
  "debug": false,
  "ssl_verify": false,
  "ssl_client": []
}
```

test event:
```
{
  "directive": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover",
      "payloadVersion": "3",
      "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"
    },
    "payload": {
      "scope": {
        "type": "BearerToken",
        "token": "access-token-from-skill"
      }
    }
  }
}
```
error log output:
```

{
  "errorMessage": "2019-04-08T16:48:05.779Z 23af2947-2be1-4751-abf0-d188a2fdc0b1 Task timed out after 10.01 seconds"
}


START RequestId: 23af2947-2be1-4751-abf0-d188a2fdc0b1 Version: $LATEST
END RequestId: 23af2947-2be1-4751-abf0-d188a2fdc0b1
REPORT RequestId: 23af2947-2be1-4751-abf0-d188a2fdc0b1	Duration: 10010.17 ms	Billed Duration: 10000 ms 	Memory Size: 128 MB	Max Memory Used: 51 MB	
2019-04-08T16:48:05.779Z 23af2947-2be1-4751-abf0-d188a2fdc0b1 Task timed out after 10.01 seconds
```

Thank you so much for taking the time to look into my case. much appreciated!

-Ahmad
