### ISSUE TITLE
Everything works but...

### ISSUE THREAD

**Issue by OrangeReaper** [mike-grant/haaska#144]
Hi.
Firstly, thanks for this. I successfully followed your instructions and have my desired functionality up and running.

However... I get the following error messages in hass.io log

`Error when sending ChangeReport to Alexa: INVALID_ACCESS_TOKEN_EXCEPTION: Access token is not valid.`

My Hass.io config is:

```
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: !secret alexa_client_id
    client_secret: !secret alexa_client_secret
    filter:
      include_entities:
        - media_player.roberts_radio
      include_domains:
        - switch
    entity_config:
      media_player.roberts_radio:
        name: Kitchen Radio
        description: Radio in the kitchen
```
Any hints on how to eliminate these errors would be gratefully received.
Thanks in advance
Andy
