### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by master-kenobi** [mike-grant/haaska#15]
@anthonylavado you have been really helpful. perhaps you can help me on this one too?

So far, the test returns no errors. I can enable the skill and link the account in the Alexa app. However, it couldn't discover any devices. I'm using HA 0.62.1 and I have this in my HA config...

```
alexa:
  flash_briefings:
    default:
      - title: Default Flash Briefing
        text: >
          {{ states('sensor.alexa_flash_briefing') }}
  smart_home:
    filter:
      include_entities:
        - fan.ceiling_fan
        - fan.fan
        - fan.play_room_fan
        - fan.wall_fan
        - fan.bedroom_fan
        - group.dining
```
Since the documentation is quite outdated, I find it quite confusing.

May I know do I need to add `haaska_hidden: false` in customize section in HA?

Thanks in advance.
