### ISSUE TITLE
[DOC] instructions don't match developer console any more.

### ISSUE THREAD

**Issue by scyto** [mike-grant/haaska#210]
This is not valid, there is no gold bar (i do have a gold colored notification about credit cards)
```
Click the gold button that reads "Create a New Security Profile".
Enter any security profile name you'd like, e.g. "haaska"
Write a short description, e.g. "haaska for my Home Assistant"
Add any url you'd like for the privacy notice, e.g. "https://myhass.example.com"
```
suggest the above is modified to say:
```
click settings
click security profiles
Click the gold button that reads "Create a New Security Profile".
Enter any security profile name you'd like, e.g. "haaska"
Write a short description, e.g. "haaska for my Home Assistant"
click save
```
note there is no field for a url any more

Alex Skill setup -  some differences here too
```
logon to devloper.amazon.com 
click alexa in the main window
click blue console button
click create skill
<rest of instructions ok>
```
this section was confusing https://github.com/mike-grant/haaska/wiki/Setting-up-haaska#setting-up-aws-lambda---part-2 should read
```
in the designer view, within your function overview, click add trigger
click select trigger and select Alexa Smart Home
<then warning about not seeing alexa smart home> 
 In the "Application ID" box, copy and paste the "Skill ID" from the Alexa Developer Console window (e.g. amzn1.ask.skill.ed66dfa4-1185-492e-bf6e-1f70e90fb018).
Make sure "Enable Trigger" is checked. Click "Add" at the bottom right.
In the "Designer" section, click code tab and then in code source box click 'upload from' and select zip

**Comment by scyto** [comment]
i will keep amending above as i figure out differences. seems like they must of rolled a new console?

**Comment by scyto** [comment]
well what a waste of time, i think this code is a abandoned? 
and this is the right place to start, they joys of your tube, open source etc :-)

**Comment by stackunderflows** [comment]
@scyto Did you actually get it to work. My labda pulls in the device info properly but Alexa can't find any of the devices.

**Comment by scyto** [comment]
Yes I got the instructions in the link I supplied above working in March. Its still working now.
Don't forget to setup your filters in yaml, something like
```
smart_home:
  locale: en-US
  endpoint: https://api.amazonalexa.com/v3/events
  client_id: !secret alexa_client_id
  client_secret: !secret alexa_client_secret
  filter:
    include_domains:
      - light
      - climate
      - lock
    # include_entity_globs:
    #   -
    # include_entities:
    #   -
```
