### ISSUE TITLE
Haaska only working while homeassistant is booting

### ISSUE THREAD

**Issue by benoegen** [mike-grant/haaska#225]
Hi, can anyone help?
Haaska is configured correctly, but the test times out and alexa cannot discover item when hassos is running.
But when I restart homeassistant, the test is showing results and alexa discory works. Once Homeassistant has finished booting, it times out again. I removed additional stuff like google, spotify, spotcast, octoprint, but this showed no effects.

Any ideas what else could cause this?

This is the stripped config:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize: !include customize.yaml

#frontend:
#  themes: !include_dir_merge_named themes

# Example configuration.yaml entry for the HTTP component
http:
  base_url: https://XXXXXXXX.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

sensor:
  - platform: template
    sensors:
      setpoint_wozi:
        value_template: "{{ states.climate.wohnzimmer.attributes.temperature | float }}"
        friendly_name: "Setpoint Wohnzimmer"
  - platform: template
    sensors:
      rockrobo_battery:
        value_template: "{{ states.vacuum.staubi_unten.attributes.battery_level | float }}"
        friendly_name: "rockrobo batterie"
        unit_of_measurement: "%"
  - platform: template
    sensors:
      temp_wozi:
        value_template: "{{ states.climate.wohnzimmer.attributes.current_temperature | float }}"
        friendly_name: "Temperatur Wohnzimmer"
        unit_of_measurement: "° C"
  - platform: time_date
    display_options:
      - "time"
  - platform: template
    sensors:
      timetomull:
        friendly_name: Time to Mull
        value_template: >-
          {% if states.calendar.mull.attributes.start_time %}
            {{((as_timestamp(states.calendar.mull.attributes.start_time) - as_timestamp(now())) / 60) | default(99) | int }}
          {%- else -%}
            0
          {%- endif %}

recorder:
  purge_keep_days: 7
  auto_purge: true
  commit_interval: 300
  db_url: !secret MariaDB
  exclude:
    entities:
      - sensor.time
      - sensor.timetomull
      - group.bewegung_treppe
    entity_globs:
      - sensor.redmi_*
      - sensor.poco*
      - binary_sensor.sensor_movement_treppe*
      - binary_sensor.redmi_note_8t*
      - sensor.fuchsbau*
    domains:
      - script

logbook:
  exclude:
    entities:
      - group.bewegung_treppe
      - sensor.time
      - sensor.timetomull
      - sensor.last_boot
    entity_globs:
      - sensor.redmi_*
      - sensor.poco*
      - binary_sensor.sensor_movement_treppe*
      - sensor.fuchsbau*
      - binary_sensor.redmi_note_8t*
    domains:
      - script

history:
  exclude:
    domains:
      - automation
      - binary_sensor
      - calendar
      - climate
      - device_tracker
      - group
      - homematic
      - input_boolean
      - input_number
      - input_select
      - light
      - media_player
      - person
      - remote
      - script
      - select
      - sensor
      - sun
      - switch
      - vacuum
      - weather
      - zone

api:

alexa:
  smart_home:
```
