### ISSUE TITLE
Alexa app can't find any devices even thought test finds then all

### ISSUE THREAD

**Issue by dexy58** [mike-grant/haaska#229]
I followed your guide on Wiki page, but for some reason Alexa cant find any devices connected to it.
This is how my configuration.yaml looks like:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

api:

alexa:
  smart_home:
    endpoint: https://api.amazonalexa.com/v3/events
    client_id: from alexa developer account permissions
    client_secret: from alexa developer account permissions
    filter:
      include_entities:
        - sensor.my_temperature_sensor
        - light.hue_color_lamp_1
        - light.hue_color_lamp_2
        - light.hue_color_lamp_3

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "::1"
    - "127.0.0.1"

sensor:
  - platform: serial
    serial_port: /dev/ttyUSB0
    baudrate: 115200

  - platform: template
    sensors:
      my_presence_sensor:
        friendly_name: Presence
        value_template: "{{ states('sensor.serial_sensor').split(',')[4].split(':')[1] | int }}"
      my_temperature_sensor:
        friendly_name: Temperature
        unit_of_measurement: "°C"
        value_template: "{{ states('sensor.serial_sensor').split(',')[0].split(':')[1] }}"
      my_humidity_sensor:
        friendly_name: Humidity
        unit_of_measurement: "%"
        value_template: "{{ states('sensor.serial_sensor').split(',')[1].split(':')[1] }}"
      my_door_sensor:
        friendly_name: Door
        value_template: "{{ states('sensor.serial_sensor').split(',')[3].split(':')[1] | int }}"
      my_luminosity_sensor:
        friendly_name: Luminosity
        unit_of_measurement: "Lux"
        value_template: "{{ states('sensor.serial_sensor').split(',')[2].split(':')[1] }}"
```
I use ngrok instead of duckdns (since I don't have HomeAssistnat Supervisor, I installed mine on a docker and I don't have addons store to download duckdns). I tested this with ngrok and it works, the test passes, I can connect to my home assistant from a different network and I can enable haaska dev skill from my android app.

On AWS, I use Europe (Ireland) for region and one of the most interesting part is that in the Wiki instructions it says to enable "Enable Trigger", but for me that doesn't exist.
![image](https://user-images.githubusercontent.com/40712374/145203235-c454b92b-945b-4bf9-9456-e3b1c61cb6f9.png)

Also, I use two different accounts. The AWS and Alexa developer console are two different accounts (the AWS ones is the one that our whole department uses and the alexa developer account is my personal, is that okay or do both AWS and Alexa need to be 1 account?)

My Alexa Dot model is EU-2338 Luxemburg (I am from Croatia). I set my Alexa Dot to English (US) as well as English (US) in Alexa skill console, however my region is Europe (Ireland). I changed to English (UK) and it still doesn't find anything.

I tried N. Virginia region, but I don't see Alexa Smart Home trigger in lambda for that region. Can someone explain how does Alexa Smart Home trigger appear? I know it has something to do with region, but how does it know where my alexa is? I don't remember configuring that at all (unless it has something to do with home assistant?).
