### ISSUE TITLE
Discovery Alexa (haaska) not work after ha upgrade

### ISSUE THREAD

**Issue by AleDestroyer** [mike-grant/haaska#261]
Hi,
I can't figure out why the discovery stopped working. I started using cloudflare instead of duckdns, I also updated the url on the lambda function. During the app test from aws it works, I put the excerpt here:

Do you see anything strange? I'm not very practical. Thanks a lot for the help
```
{
  "url": "https://xxxxxxxx/api",
  "bearer_token": "xxxxxxxxxxxxxxxx",
  "debug": false,
  "ssl_verify": false,
  "ssl_client": []
}
```
```
Response
{
  "event": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover.Response",
      "messageId": "dc2577bc-c8d0-47cc-a2db-4552575b9a10",
      "payloadVersion": "3"
    },
    "payload": {
      "endpoints": [
        {
          "displayCategories": [
            "INTERIOR_BLIND"
          ],
          "cookie": {},
          "endpointId": "cover#tapparellecasa",
          "friendlyName": "TapparelleCasa",
          "description": "cover.tapparellecasa via Home Assistant",
          "manufacturerName": "Home Assistant",
          "additionalAttributes": {
            "manufacturer": "Home Assistant",
            "model": "cover",
            "softwareVersion": "2024.8.3",
            "customIdentifier": "-cover.tapparellecasa"
          },
          "capabilities": [
            {
              "type": "AlexaInterface",
              "interface": "Alexa.PowerController",
              "version": "3",
              "properties": {
                "supported": [
                  {
                    "name": "powerState"
                  }
                ],
                "proactivelyReported": true,
                "retrievable": true
              }
            },
            {
              "type": "AlexaInterface",
              "interface": "Alexa.RangeController",
              "version": "3",
              "instance": "cover.position",
              "properties": {
                "supported": [
                  {
                    "name": "rangeValue"
                  }
                ],
                "proactivelyReported": true,
                "retrievable": true,
                "nonControllable": false
              },
              "capabilityResources": {
                "friendlyNames": [
                  {
                    "@type": "text",
                    "value": {
                      "text": "Position",
                      "locale": "en-US"
                    }
                  },
                  {
                    "@type": "asset",
                    "value": {
                      "assetId": "Alexa.Setting.Opening"
                    }
                  }
                ]
              },
              "configuration": {
                "supportedRange": {
                  "minimumValue": 0,
                  "maximumValue": 100,
                  "precision": 1
                },
                "unitOfMeasure": "Alexa.Unit.Percent"
              },
              "semantics": {
                "actionMappings": [
                  {
                    "@type": "ActionsToDirective",
                    "actions": [
                      "Alexa.Actions.Lower",
                      "Alexa.Actions.Close"
                    ],
                    "directive": {
                      "name": "SetRangeValue",
                      "payload": {
                        "rangeValue": 0
                      }
                    }
                  },
                  {
                    "@type": "ActionsToDirective",
                    "actions": [
                      "Alexa.Actions.Raise",
                      "Alexa.Actions.Open"
                    ],
                    "directive": {
                      "name": "SetRangeValue",
                      "payload": {
                        "rangeValue": 100
                      }
                    }
                  }
                ],
```

![Immagine 2024-09-03 083208](https://github.com/user-attachments/assets/7e8b1110-06e2-43f7-8759-9466021284dc)

This is the configuration.yaml part

```
api:
alexa:
  smart_home:
    filter:
      exclude_domains:
        - alert
        - automation
        - binary_sensor
        - button
        - camera
        - climate
        - cover
        - device_tracker
        - fan
        - group
        - humidifier
        - input_boolean
        - input_button
        - input_datetime
        - input_number
        - input_select
        - light
        - lock
        - number
        - person
        - remote
        - select
        - sensor
        - siren
        - switch
        - timer
        - vacuum
        - weather
        - zone
        - media_player
        - scene
        - light
      include_domains:
        - alarm_control_panel
        - script
      include_entities:
        - cover.tapparellecasa
        - cover.tapparellecucina
        - switch.sirene
```
