### ISSUE TITLE
Alexa Climate Thermostat State "off / deactivate" not handled.

### ISSUE THREAD

**Issue by sheggy012** [mike-grant/haaska#99]
**Home Assistant release with the issue:**
version: 0.89.2

**Last working Home Assistant release (if known):**
not known

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io

**Component/platform:**
Alexa with Climate Platform in combination via Haaska

```yaml
climate:
  - platform: generic_thermostat
    name: Badezimmer Thermostat
    heater: switch.fibaro_fgs223_bad
    target_sensor: sensor.temperatur_bad
    min_temp: 15
    max_temp: 30
    ac_mode: false
    target_temp: 22
    cold_tolerance: 0.3
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 5
    keep_alive:
      minutes: 3
    initial_operation_mode: "off"
    away_temp: 16
    precision: 0.1
```

**Description of problem:**
Thermostat operation mode "off"  returns "not supported".
Cooling and Heating ist working fine. 

Here is a example, language is in German: 
Me: badezimmer thermostat heizen
Alexa: Es ist auf heizen gestellt / It is set to heat            #(Alexa sets Thermostat to Heating)
Me: badezimmer thermostat kühlen
Alexa: Badezimmer Thermostat reagiert gerade nicht. / is not responding.    #(Thermostat doesn't support cooling, so this ist also fine)
Me: badezimmer thermostat off
Alexa: Badezimmer Thermostat unterstützt das nicht. / does not support that.
Me: badezimmer thermostat deaktivieren
Alexa: Badezimmer Thermostat unterstützt das nicht. / does not support that.
Me: badezimmer thermostat ausschalten
Alexa: Badezimmer Thermostat unterstützt das nicht. / does not support that.

In the last 3 attempts alexa ist not even trying to change the state. Home Assistant doesn't recive any request. It feels like the Haaska component doesn't understand the commands to disable or deactivate the climate thermostat.
